# Generated by Django 5.2.4 on 2025-07-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255)),
                ('latest_price', models.DecimalField(blank=True, decimal_places=2, help_text='The latest price recorded for the product.', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage', max_digits=5, null=True)),
                ('source_url', models.URLField(help_text='The unique URL of the product on the source website.', max_length=1024, unique=True)),
                ('image_url', models.URLField(blank=True, help_text="URL of the product's image.", max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the product currently available on the source site?')),
                ('category', models.CharField(blank=True, help_text='Product category (optional for v0.1).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price recorded at the time of scraping.', max_digits=10)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='deal_board.product')),
            ],
        ),
    ]
