# Generated by Django 5.2.4 on 2025-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Discount percentage', null=True),
        ),
    ]
