# Generated by Django 5.2.4 on 2025-08-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_board', '0002_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_url', models.URLField(max_length=1024)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_listings', to='deal_board.product')),
            ],
        ),
    ]
