# Generated by Django 5.2.5 on 2025-08-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_board', '0003_ebaylisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='latest_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The current price of the product.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Unknown', help_text="Product category (defaults to 'Unknown' if extraction fails).", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=500),
        ),
    ]
