# Generated by Django 5.2.5 on 2025-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_board', '0004_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_ebay_check',
            field=models.DateTimeField(blank=True, help_text='Last time eBay listings were checked for this product.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(help_text='Discount percentage'),
        ),
    ]
